name: Node JS workflow1.1

on:
  push:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  myJob1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci 
      - run: ls
