name: Node JS workflow

on:
  push:
    branches: ["main"]

jobs:
  myJob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: ls
