name: Node JS workflow

on:
  push:
    branches: ["main"]

jobs:
  myJob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'echoingTest'
        run: echo "this is a test!"
